# Generated by Django 3.1.2 on 2020-10-11 10:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='puplished_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 11, 10, 49, 14, 851982, tzinfo=utc), verbose_name='date published'),
        ),
    ]
